### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by lich13** [RoxasShadow/SauceNao-Windows#2]
Thank you for your help.
![default](https://cloud.githubusercontent.com/assets/10644698/19017476/9e38e772-886d-11e6-8a43-be820c6ac3f3.PNG)
![1](https://cloud.githubusercontent.com/assets/10644698/19017478/9e777df2-886d-11e6-8b10-9627655a29c9.PNG)

**Comment by winterthediplomat** [comment]
Hello @lich13, during my tests I noticed that imgur requires the `client id`, not the `client secret` that you've set in the configuration. The `client id` is the short one, that you can retrieve at [your imgur Applications settings](https://imgur.com/account/settings/apps).
I suggest changing your IMGUR_API_KEY to that.

The patch that is referenced in this thread should fix the problem (imgur API changed). If it works for you, @RoxasShadow will be very happy to merge it.

**Comment by lich13** [comment]
@alfateam123 Thank you for your help.Actually, I've tried the two id before. It still can't work
![default](https://cloud.githubusercontent.com/assets/10644698/19024606/402d60c8-8939-11e6-86eb-46e17d2ef2f7.PNG)

**Comment by winterthediplomat** [comment]
@lich13 I built a [pre-release package](https://github.com/alfateam123/SauceNao-Windows/archive/patch-issue-2.zip), that is available [at my fork](https://github.com/alfateam123/saucenao-windows/releases) too.
I tested the pre-release package using your credentials: everything worked on two different computers (win10 and win7).

Could you please test the pre-release package on your computer? Download it, unpack it and update your `regedit.bat` to set `SAUCENAO` to the pre-release binary. If it works, @RoxasShadow will merge the PR referenced in this thread and make the patch available to everyone.

![it_works](https://cloud.githubusercontent.com/assets/1429402/19051425/56d0a950-89b3-11e6-84e8-cffe4c07ec17.png)

**Comment by lich13** [comment]
@alfateam123 It still cant work but I made a bat to get the log this time.I changed my saucenao_api_key.
@echo off
set PATH=%~dp0\;%PATH%
SauceNao-Windows.exe 61a152a5493710391472211b141b6372b8d59325 dd20ec720f97ed0 D:\Documents\Pictures\0a6hl7Qz.png 127.0.0.1: >log.txt 2>error.txt
error:

Unhandled Exception: System.Net.WebException: An exception occurred during a WebClient request. ---> System.IO.IOException: Unable to write data to the transport connection: 远程主机强迫关闭了一个现有的连接。. ---> System.Net.Sockets.SocketException: 远程主机强迫关闭了一个现有的连接。
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.WebClient.UploadBitsState.WriteBytes()
   at System.Net.WebClient.UploadBits(WebRequest request, Stream readStream, Byte[] buffer, Int32 chunkSize, Byte[] header, Byte[] footer, CompletionDelegate uploadCompletionDelegate, CompletionDelegate downloadCompletionDelegate, AsyncOperation asyncOp)
   at System.Net.WebClient.UploadValues(Uri address, String method, NameValueCollection data)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.UploadValues(Uri address, String method, NameValueCollection data)
   at System.Net.WebClient.UploadValues(String address, NameValueCollection data)
   at SauceNao_Windows.Imgur.Upload(String path, String apiKey) in C:\Users\alfateam\Documents\wowo\saucenao\SauceNao-Windows\Imgur.cs:line 20
   at SauceNao_Windows.Program.Main(String[] args) in C:\Users\alfateam\Documents\wowo\saucenao\SauceNao-Windows\Program.cs:line 38

**Comment by winterthediplomat** [comment]
interesting error. gtranslate says "remote host forcibly closes an existing connection". it may be a problem with your connection/proxy setup, but I'll try.

do you have a proxy on 127.0.0.1:80 or is that a typo? you can remove the proxy parameter if you don't have one.
if you set the same proxy in a browser (firefox, chrome...), will it connect to imgur.com?
if you try several times (more than once), will you **always** get the socket error?

will try at work (i have a proxy there), but everything works _without_ a proxy, so I think these are connection/proxy issues.

**Comment by lich13** [comment]
I have a proxy on 127.0.0.1:9999.
I use it in firefox and chrome both can connect to imgur.com.
I try 10+ times and try removing the proxy always get the socket error.
![default](https://cloud.githubusercontent.com/assets/10644698/19063634/2bd6beb8-8a37-11e6-93cf-d3440278d90d.PNG)
@alfateam123

**Comment by winterthediplomat** [comment]
I had a moment to try the application at work, and it works correctly. I had a problem with saucenao because I set a wrong proxy ("unable to connect to remote server"), but after fixing it everything worked like a charm.

Please, be sure to set the proxy correctly. In the script you showed (copy-pasted for reference), the port after the ip is missing.

```
@echo off
set PATH=%~dp0\;%PATH%
SauceNao-Windows.exe 61a152a5493710391472211b141b6372b8d59325 dd20ec720f97ed0 D:\Documents\Pictures\0a6hl7Qz.png 127.0.0.1: >log.txt 2>error.txt
```

The real script should be (please notice the PROXY parameter now has the port):

```
@echo off
set PATH=%~dp0\;%PATH%
SauceNao-Windows.exe 61a152a5493710391472211b141b6372b8d59325 dd20ec720f97ed0 D:\Documents\Pictures\0a6hl7Qz.png 127.0.0.1:9999 >log.txt 2>error.txt
```

If it does not work after that change, I'd suggest investigating any possible problem in your environment.

**Comment by winterthediplomat** [comment]
hello @lich13, does everything work now? some feedback would be appreciated :)

**Comment by lich13** [comment]
@alfateam123 There's still the same bug. I've given up lol
